ceph_iscsi_config/client.py, ceph_iscsi_config/common.py, ceph_iscsi_config/utils.py, gwcli.8, gwcli/gateway.py
Configuration will be handled by 'gwcli' and the Ceph Dashboard.
=> Drop support for ansible target/initiator/LUN configuration

.gitignore, README, README.md, ceph-iscsi.spec, ceph_iscsi_config/client.py, test/test_chap.py, tox.ini
=> chap: migrate from python-crypt to python-cryptography

rbd-target-api.py
Signed-off-by: tangwenji <tang.wenji@zte.com.cn>
=> API:add rpm name in log when rpm check failed

ceph_iscsi_config/lun.py, rbd-target-api.py
This PR fixes 2 python3 issues.
=> Fix python3 issues

ceph-iscsi.spec, ceph_iscsi_config/backstore.py, ceph_iscsi_config/client.py, ceph_iscsi_config/common.py, ceph_iscsi_config/discovery.py, ceph_iscsi_config/gateway.py, ceph_iscsi_config/gateway_object.py, ceph_iscsi_config/group.py, ceph_iscsi_config/lio.py, ceph_iscsi_config/lun.py, ceph_iscsi_config/metrics.py, ceph_iscsi_config/utils.py, gwcli/ceph.py, gwcli/client.py, gwcli/gateway.py, gwcli/hostgroup.py, gwcli/node.py, gwcli/storage.py, gwcli/utils.py
This PR adds some conditionals to the spec file to support the packaging in openSUSE based distros.
It also cleans up a bit the spec file, and also deletes python interpreter shebangs in non-executable python files.
=> spec: opensuse support

rbd-target-api.py
=> Expose gateway hostname info in /api/sysinfo controller

rbd-target-gw.py
=> gw: use client id when calling ceph shell command

ceph-iscsi.spec
=> spec: add python-configshell runtime depedency

ceph_iscsi_config/lun.py, ceph_iscsi_config/utils.py, gwcli/ceph.py, gwcli/storage.py, rbd-target-api.py
=> Always use rados client name when connecting to Ceph cluster

ceph_iscsi_config/client.py, gwcli/client.py, gwcli/utils.py, rbd-target-api.py
This new endpoint will expose `alias`, `ip_address` and `state` of the client session.
Additionally, this PR also includes the following changes (related to the multi-target support):
- The `logged_in` information displayed in the `gwcli` will now display the information for the "current" target only (instead of displaying the info from the first session found regardless of the target that the client is connected in that session)
- The validation that checks if a client is logged in before allowing to delete him will now consider the target IQN.
=> Adds `/api/clientinfo/<target_iqn>/<client_iqn>` endpoint (and more...)

ceph_iscsi_config/lun.py, rbd-target-api.py
Note that, despite being supported, 'Journaling' is not enabled by default.
=> Journaling is a supported RBD feature

ceph_iscsi_config/target.py
Since https://github.com/ceph/ceph-iscsi/pull/51 we are now able to delete a gateway, but if we try to delete the target after deleting all gateways we will receive an error because the target does not exist in the LIO config.
This PR will allow deleting a target that exists in the `gateway.conf` but does not exist in LIO.
**How to reproduce:**
```
/iscsi-targets> create iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw
ok
/iscsi-targets> cd iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw/gateways
/iscsi-target...-igw/gateways> create node1 192.168.100.201 skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
ok
/iscsi-target...-igw/gateways> delete node1 confirm=true
Deleting gateway, node1
/iscsi-target...-igw/gateways> cd .. …
```
=> Should be possible to delete a target that does not exist in LIO

rbd-target-api.py
If iSCSI port is down or not listening, the 'call_api' will return an HTTP 503 code.
In the context of 'targetinfo' endpoint this should not be considered an error because if this happens we can assume that there are no active sessions.
=> Fix 'targetinfo' endpoint when iSCSI port is down

README.md
gwcli, rbd-target-api and rbd-target-gw are installed by setup.py.
=> Update manual install instructions

gwcli/storage.py, rbd-target-api.py
Just some misc lun/image creation related fixes.
=> Misc lun/image creation fixes

gwcli/ceph.py
The output of `ceph -s -f json` has changed in https://github.com/ceph/ceph/pull/29493, so `gwcli` has to be adapted accordingly. 
Fixes: https://github.com/ceph/ceph-iscsi/issues/141
=> Fix `gwcli` error on octopus

ceph_iscsi_config/common.py
[edit: updated description to indicate this also fixes issue 2]
This fixes 2 bugs:
1. While we are in version 9.5, the config watch would detect the
version being updated to 9.5 then swing back on us. We only check for
full version upgrades so we would end up updating the version again and
looping like this until the other nodes were updated.
2. If upgrading from 9 to version > 10, the new versions added fields
that were then later refefenced when setting up the target. If all the
gws did not upgrade quickly enough, like with a rolling upgrade, then
the config watch might not have detected the config change and updated
us to 11 and added the new fields. We would then crash.
This patch skips the intermediate version 9.5 and checks if the node is
in the gateways_upgraded list or not to …
=> Fix 9 to 10 upgrade

ceph_iscsi_config/target.py
Signed-off-by: wuxingyi <wuxingyi2015@outlook.com>
=> don't store to config if create_target fails

ceph_iscsi_config/client.py, ceph_iscsi_config/common.py, ceph_iscsi_config/lun.py, ceph_iscsi_config/metrics.py, gwcli/utils.py
=> Fixed numerous string format issues on errors paths

ceph_iscsi_config/target.py
=> Fix list access violiation when load config

ceph_iscsi_config/settings.py, rbd-target-api.py
When we are dealing with things like `trusted_ip_list` but ceph-iscsi is
running in a container modifying the list can be problematic. Sure the
config file is mounted into the container, but getting users to modify
that isn't very user friendly.
What would be better is if you could store the value in the mon config
key store. But then why stop at just the `trusted_ip_list`, ceph-iscsi's
settings are already fairly dynamic. So instead treat any value starting
with `config://` as a key for config key store.
This obviously wont work for the client name or the ceph conffile as we
need those to talk to the key store, but means anything else in the
config, if you so choose, can come from the dynamic ceph config store.
For example, if I had:
trusted_ip_list = config://some/key/you/want/to/use …
=> Make settings mon config key store aware

rbd-target-api.py
Fixes: https://tracker.ceph.com/issues/48541
=> rbd-target-api: misc fixing for disk API

gwcli/gateway.py
=> gwcli: add error handling path for config api request.

README
=> README: add IPv6 related info
