- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/lun.py
- ceph_iscsi_config/settings.py
- ceph_iscsi_config/utils.py
- gwcli/ceph.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/storage.py
- rbd-target-api.py
- rbd-target-gw.py
This PR adds support for Python3, ensuring that Python2 continues to work.
> Add support for Python3

- rbd-target-api.py
With this PR, all API exceptions will be logged into `rbd-target-api.log` file.
> Use the correct logger to log API exception

- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
This PR will fix the following error when performing a disk operation on a machine that is not a valid gateway:
`Failed : Unhandled exception: list.remove(x): x not in list`
**How to reproduce**
Given the following configuration:
```
o- disks .............................................................. [0.00Y, Disks: 0]
o- iscsi-target ............................................................ [Targets: 1]
o- iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw ............................ [Gateways: 2]
o- gateways ................................................... [Up: 2/2, Portals: 2]
| o- node2 ................................................... [192.168.100.202 (UP)]
| o- node3 ................................................... [192.168.100.203 (UP)]
o- host-groups …
```
> Fix errors when performing operations on invalid gateway

- ceph_iscsi_config/lun.py
- gwcli/client.py
- gwcli/storage.py
- rbd-target-api.py
User should be able to create a disk using an existing RBD image, but in this case, it doesn't make sense to force the user to specify the disk size.
This PR will make the `size` parameter optional when image already exists.
Note that in Ceph Manager Dashboard we will use images that were previously created on the dedicated `Block > Images` page.
> Disk size is optional if image already exists

- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/discovery.py
- ceph_iscsi_config/gateway.py
- ceph_iscsi_config/gateway_object.py
- ceph_iscsi_config/group.py
- ceph_iscsi_config/lio.py
- ceph_iscsi_config/lun.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/hostgroup.py
- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
- rbd-target-gw.py
- test/test_common.py
- test/test_group.py
This PR adds support for multiple iSCSI targets.
**Some other changes included in this PR:**
- Add `detach <disk>` command
(similar to `delete <disk>` but will not delete the RBD image)
- Add `attach <disk>` command
(similar to `create <disk>` but will not create the RBD image)
- Lazy creation of LIO storage objects
(LIO storage objects will only be created when mapped to a target)
- Allow disk deletion from a `gwcli` running on any host
(instead of forcing the user to connect to the disk allocating host)
- Mutual chap authentication
- Discovery authentication (chap and chap_mutual)
> Multiple iSCSI target support (and more...)

- ceph_iscsi_config/client.py
The keys() returns a dict_keys and not a list.  The GWClient.__init__
throws a Type Error on isinstance(image_list[0],...).  This prevents the
service from starting.
Signed-off-by: Eric Jackson <swiftgist@gmail.com>
> Fix restart of rbd-target-gw service

- rbd-target-api.py
After a sequence of multiple REST Api calls to create gateways, I ended up with an inconsistent `ip_list` in the configuration:
**How to reproduce:**
1) API call to create gateway **node1 192.182.100.201**
2) API call to create gateway **node2 192.182.100.202**
3) API call to create gateway **node3 192.182.100.203**
Looking into the configuration we can see that `192.182.100.202` is missing in the `ip_list`, but `node2` was added:
```
...
targets": {
"iqn.2003-01.com.redhat.iscsi.gw:1547740766118": {
"ip_list": [
"192.168.100.201",
"192.168.100.203"
],
"portals": {
"node1": {...},
"node2": {...},
"node3": {...},
...
```
This is caused by a missing `config.refresh()`.
> Fix race condition on gateway creation

- ceph_iscsi_config/client.py
- ceph_iscsi_config/gateway.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/utils.py
- rbd-target-api.py
The iSCSI spec defines the initiator/target names as case insensitive and rtslib will convert capital letters to lower case. If the user passes in upper case we will store that non-normalized format in gateway.conf then later try to match that with the rtslib/kernel value. So we can end up creating clients/targets with capital letters but not remove them.
This patch series has us normalize and use that name at the gwcli/user level, API layer and lib/ceph-iscsi-config layers, so if it is user input or an app creating these objects we will always use the value rtslib and the kernel uses.
> Use normalized iscsi names

- rbd-target-api.py
This will ensure that the returned config is always up-to-date regardless of where changes were made.
> Config API should always attempt a config refresh

- rbd-target-api.py
This PR adds a missing `config.refresh()` after group deletion.
> Fix race condition on group deletion

- rbd-target-api.py
How to reproduce (starting with a clean configuration):
1. API call to create target on node1
2. API call to create gateway node1 192.182.100.201
3. API call to create gateway node2 192.182.100.202
Sometimes it fails on step `3` because the newly created target doesn't exist in the node2 config yet
> Fix race condition after target creation

- ceph_iscsi_config/lun.py
- gwcli/storage.py
- rbd-target-gw.py
This will guarantee that `/iscsi-targets/<target>/disks` `help` command will provide the correct information about the `disk` param, and an appropriate message will be displayed if the user execute `add` or `delete` command without specifying the disk.
> Disk is a required param when adding/deleting targetlun

- rbd-target-gw.py
- usr/lib/systemd/system/rbd-target-gw.service
This change is required to avoid a problem originated when running
setuptools with the --executable option to override the shebang
of the pyhton script when the original file has a shebang with a
parameter.
Example:
original file has:
Running python setup.py --executable=/usr/bin/pyhton -s will generate
an executable file with:
which is not a valid shebang.
> packaging: Move python unbuffered option to systemd unit file

- rbd-target-api.py
This PR fixes a regression introduced during the implementation of the `attach <disk>` command, causing the ignore of the size provided by the user in the `resize <disk> <size>` command.
> Disk resize has no effect

- ceph_iscsi_config/backstore.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/lun.py
- gwcli/storage.py
- rbd-target-api.py
- test/test_common.py
**Motivation**
In _openSUSE_, we have 2 different "backstores" so we have to patch `ceph-iscsi` in order to support the `kernel-lio-rbd` in addition to the already supported `tcmu-runner`.
**Proposed Solution**
With this PR, `ceph-iscsi` will continue to only support `tcmu-runner` but the code (and `gateway.conf`) will be prepared to easily add support for a different backstore.
This proposed change will not only simplify the _openSUSE_ patch, but also be useful if, in the future, `ceph-iscsi` has to support any additional backstore.
> Adds infrastructure for multiple backstores

- rbd-target-api.py
This PR will use gateway `names` instead of portal `IPs` when calling `_gateway` endpoint, just like it's being done in other `call_api` invocations.
Using IPs instead of names may end up in an error that can be reproduced with the following steps:
1) Assume the following environment:
- node1: 192.168.100.201 _(Flask/Api address)_
- node2: 192.168.100.202 _(Flask/Api address)_, 192.168.121.56 _(Other address)_
2) Try to create execute the following:
```
vagrant@node1:~> sudo gwcli
/iscsi-targets> create iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw
ok
/iscsi-targets> cd iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw/gateways
/iscsi-target...-igw/gateways> create node1 192.168.100.201 skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
ok …
```
> Fix '_gateway' call to use names instead of IPs

- ceph-iscsi.spec
Drop tabs for spaces, update the `License` to `GPLv3+`, use the `%autosetup` macro, and add Python 3 support for Fedora and RHEL 8.
> rpm packaging fixes

- ceph_iscsi_config/gateway_object.py
- ceph_iscsi_config/lun.py
- rbd-target-api.py
According to [this conversation](https://github.com/ceph/ceph-iscsi/commit/893aada629b25032fb438dd0041e3aada31d138e#r32383227), this PR will optimize the lun mapping by executing the `LUN.allocate` method in the current lun only, instead of executing it for all luns (through the `LUN.define_luns` method).
This PR also includes one additional commit that will prevend double `config.commit` during the execution of the `LUN.allocate` method.
> Optimize LUN mapping

- ceph_iscsi_config/settings.py
ATM, controls with value `0` are being ignored.
This PR adds support for `zero` value in controls.
> Support controls with value `0`

- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/gateway.py
- gwcli/client.py
- rbd-target-api.py
- test/test_common.py
Initiator name based ACL authentication can now be disabled using the `auth noacl` command (if the target doesn't contain clients).
ACL authentication will be automatically re-enabled if one client is added to the target.
> Adds support for disabling ACL authentication

- ceph_iscsi_config/common.py
- ceph_iscsi_config/lun.py
- ceph_iscsi_config/settings.py
- ceph_iscsi_config/utils.py
- iscsi-gateway.cfg_sample
- rbd-target-api.py
With this PR, the `pool name` used to store the `gateway.conf` can be configured in `/etc/ceph/iscsi-gateway.cfg` file (defaults to `rbd`).
> Makes pool name configurable

- ceph_iscsi_config/common.py
- ceph_iscsi_config/settings.py
- gwcli/ceph.py
- gwcli/storage.py
- iscsi-gateway.cfg_sample
Currently ceph-iscsi services will always try to connect to the cluster as `client.admin` client. This PR allows to change that.
> Add support for specifying cluster client name

- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/discovery.py
- ceph_iscsi_config/gateway.py
- ceph_iscsi_config/group.py
- ceph_iscsi_config/lun.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/utils.py
- rbd-target-api.py
- test/test_chap.py
- test/test_common.py
Using a `/` to separate the username from the password is very restrictive and will not work if we are migrating from an environment that already has users created (which may contain 'slashes').
This PR changes `auth` commands and `discovery_auth` command to use separate parameters for username/password
The password validation will now accept '/'s.
The configuration structure changed in a way that will not depend on the '/' char in the CHAP string.
**Before (example):**
Command
```
auth chap=myusername/mypassword chap_mutual=mymusername/mympassword
auth myusername/mypassword mymusername/mympassword
```
Config
```
{
"discovery_auth": {
"chap": ""
"mutual_chap": ""
}
"targets": {
"iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw": {
"clients": {
"iqn.1994-05.com.redhat:rh7-client": {
"auth": { …
```
> Support passwords with '/' (and more...)

- ceph_iscsi_config/gateway.py
We must convert exception to string before testing.
Note: In some versions of python we do not seem to have to do the
explicit conversion with a str() call and it is done automagically for
us. I am not sure what versions/why. It seems safe to always do the str() conversion.
This is probably why someone saw the exception get passed upwards as we were not matching the string comparison test.
> Fix lun exists check

- gwcli/gateway.py
- rbd-target-api.py
Just 2 fixes for target/acl reconfigure handling.
1. Fix refresh after a successful reconfigure call.
2. Make sure ACL/clients are present when reconfiguring their settings, so we can make sure they are valid values.
> Misc target/acl reconfigure fixes

- rbd-target-api.py
This was detected while using Ceph Dashboard to create an iSCSI target.
**Example:**
In this example, the Dashboard will always call the API on *node1*, to perform the following operations:
1) create target 
2) create gateway node1
3) create gateway node2
4) create gateway node3
5) disable ACL authentication
Because at step 5, node1 was not yet aware of the existance of node3 in the configuration, the `/targetauth` saved an outdated configuration that does not contain node3, so this portal was lost from the configuration (but was created in LIO).
By doing this `config.refresh` in the end of gateway creation, we guarantee that any next operation on *node1* API will use the latest config.
> Fix race condition after gateway creation

- ceph_iscsi_config/common.py
In commit:
commit b4dd88e154c0f36f1b32a596ba539650ce173112
Author: Ricardo Marques <rimarques@suse.com>
Date:   Wed Feb 27 18:32:12 2019 +0000
Support passwords with '/'
we just forgot to do a update_item for the target that we were updating clients for. This results in rbd-target-gw crashing with a keyvalue exception when it tries to get "username" but the old chap string is there.
> Fix chap config update

- ceph_iscsi_config/lun.py
The patch
commit 8b8f29af98cd1f59a58901ad3ff9c1573ff1a27a
Author: Mike Christie <mchristi@redhat.com>
Date:   Sat Mar 16 03:44:44 2019 -0500
Only map the activated disk
added a regression where when doing a reconfig we can crash because the storage object is not set. This has us set the so when we have to add it ourself.
> regression: fix lun reconfigure failure

- rbd-target-api.py
This PR changes the '/settings' endpoint to return two additional fields: "required" and "supported" features for each backstore.
> '/settings' endpoint return required and support RBD features by backstore

- ceph_iscsi_config/client.py
- ceph_iscsi_config/target.py
This is a fix for PR https://github.com/ceph/ceph-iscsi/pull/24 where we only set the `generate_node_acls` and forget to set the `demo_mode_write_protect` attribute too.
> Enable/disable 'demo_mode_write_protect' when enabling/disabling ACL authentication.

- ceph_iscsi_config/target.py
- rbd-target-api.py
This PR adds a new endpoint that can be used to get "additional" target information (info that is not included in the config file).
For now, this endpoint is only returning the number of active sessions.
This information can be used, for instance, to be displayed in the Ceph Dashboard:
> Adds `/api/targetinfo/<target_iqn>` endpoint

- ceph_iscsi_config/common.py
Fixes: https://github.com/ceph/ceph-iscsi/issues/61
> Fix upgrade from config v3 when 'controls' field is missing

- rbd-target-api.py
For now, this endpoint only returns the number of
active sessions on the local gateway.
> Adds '/api/gatewayinfo' endpoint

- gwcli/gateway.py
Even if we don't have any iSCSI target in the configuration, it should be possible to export the config because it contains other useful information like the `version`, `discovery_auth`, etc..:
```
node1:~ # gwcli export 
{
"created": "2019/04/24 08:52:19",
"discovery_auth": {
"mutual_password": "wJve8EKy4qY4begYYbLf3FXoSy6+eSKqVhlYFv6nAF1N0YTjqZYuXcONgzp53T4fNnBH9H8XuFwUadleUcn+Jtx4c/wfFfnWx+wcbSNWIHOscChFY2X1jM9Kh4z3Mgo4ovWw3ogo/i5AjOD45+UBa18BlyQtS5aH/foIkS/FvKwRKrI7El/ffi+F8V9Vn0Gv7zNccLzBMDwIn3pvUBpF8N6LwmgWmUPN7ftibKQ/j3xqcylIiHyt6pnzcQKoD7CHSma/ZnMpyB2v9bn1Q+ttXDTb3bt0K5gSX6pgtSoimrTPQZ3omNesYeT9+vwWxgDjkLofE5fzGSFyJNrKo1Im9w==",
"mutual_password_encryption_enabled": true,
"mutual_username": "cccccccc",
"password": "s5XdfBe2KZiLb9ztOdBLCI9AUayUpycKNLY9EplfMKN+L2BNpVWBvqOejOCFQc60Ndo …
```
> Should be possible to export config without targets

- ceph_iscsi_config/target.py
Check if the target already exists in ConfigFs before trying to get the number of active sessions.
> Prevent error getting the number of active sessions

- ceph_iscsi_config/target.py
- rbd-target-api.py
Target configuration can only be updated by the same gateway that performs the config "commit", otherwise, we will end up with pending transactions that will silently be committed in future requests.
It may happen that these pending transactions will remove items from the target config that were added in the meanwhile (e.g. disks).
> Fix config update in '_targetauth' endpoint

- gwcli/client.py
This PR fixes a regression introduced in PR https://github.com/ceph/ceph-iscsi/pull/57.
How to reproduce using a "3 nodes" environment:
1) create target **"A"** with 2 portals: **"node2"** and **"node3"**
2) in **"node1"** execute `gwcli ls`
3) you will see the following error
`No such Target in configfs: /sys/kernel/config/target/iscsi/iqn.2019-02.ch.migroszh:vmware-p-hdd-data`
The full traceback is:
```
File "/usr/bin/gwcli", line 194, in <module>
main()
File "/usr/bin/gwcli", line 125, in main
shell.run_interactive()
File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 905, in run_interactive
self._cli_loop()
File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 734, in _cli_loop
self.run_cmdline(cmdline)
File …
```
> Fix error when trying to get client info from `gwcli`

- ceph_iscsi_config/common.py
- ceph_iscsi_config/gateway.py
- ceph_iscsi_config/target.py
- gwcli/gateway.py
- test/test_common.py
PR https://github.com/ceph/ceph-iscsi/pull/51 introduced the support for deleting a gateway but doesn't consider the case where the gateway was created with multiple IPs.
This PRs will guarantee that when deleting a gateway, all IPs of that gateway are removed.
Create a target:
`curl --insecure --user admin:admin -X PUT https://192.168.100.201:5001/api/target/iqn.2003-01.com.redhat.iscsi-gw0`
Create one gateway with a single IP:
`curl --insecure --user admin:admin -d ip_address=192.168.100.201 -dskipchecks=true -X PUT https://192.168.100.201:5001/api/gateway/iqn.2003-01.com.redhat.iscsi-gw0/node1`
Create another gateway with **two IPs** separated by a ',':
`curl --insecure --user admin:admin -d ip_address=192.168.100.202,192.168.121.120 -dskipchecks=true -X PUT …
> Fix deletion of gateways with multiple IPs

- usr/lib/systemd/system/rbd-target-api.service
- usr/lib/systemd/system/rbd-target-gw.service
rbd-target-api and rbd-target-gw used to both be able to modify the
system, so we bound api to gw so if gw went down api would be stopped
too. This prevented races where if gw started back up api could also be
modifying the system at the same time.
When we moved the target start up code to api, we no longer had this
issue, but I forgot to update the systemd deps. This patch modifies them
so:
1. gw is bound to api. This is not required to prevent modification
races like before, but if api is stopped then the system will not have
any running target so I do not think there is no point in having gw up.
2. gw is now sarted after api. We used to need the reverse because gw
did the initial setup. Now gw needs the system setup to handle statistic
calls.
Signed-off-by: Mike Christie …
> rbd-target-api/gw: Fix systemd deps

- README
- README.md
Just update the READMEs to reflect that most functionality moved from
rbd-target-gw to rbd-target-api. Also drop ansible reference because
ceph-iscsi currently does not work with it.
> Update rbd-target-gw/api info in READMEs

- ceph_iscsi_config/client.py
- rbd-target-api.py
At the moment, Ceph Dashboard is not displaying the "logged-in" information for each client but I anticipate that the same problem described in https://github.com/ceph/ceph-iscsi/pull/74 will start happening when we start displaying that information, so I'm proposing to remove the "portal" validation from `_clientinfo` too.
> `_clientinfo` should not validate if `local_gw` is a portal

- rbd-target-api.py
**Problem**
The problem is that the Ceph Dashboard is periodically querying `ceph-iscsi` to get the number of active sessions, and sometimes during deletion of a gateway Ceph Dashboard receives an error saying that "portal nodeX is not a portal of target Y".
This happens because when we call the `targetinfo` endpoint the `portal nodeX` exists but was removed before the call to `_targetinfo` on nodeX.
**Proposed solution**
I think that the simplest solution for this problem is to simply remove this validation and assume that if `_targetinfo` is called in a node that is not a portal of that target, the number of sessions on that node is zero.
> `_targetinfo` should not validate if `local_gw` is a portal

- ceph-iscsi.spec
This updates our spec to use systemd scriptlets for fedora/RHEL.
They are described here:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/
There is one major behavior change with this patch. I followed the doc
assuming we wanted to get into fedora/RHEL. The problem is that this doc:
https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/
lists requirements for enabling the service when the package is
installed and we do not meet them, so this patch does not enable us
by default.
However, I can just update the docs for this. The upstream/RHCS docs
already state we must enable rbd-target-api so we just need to add
a line about also enabling rbd-target-gw.
> Update spec to use systemd scriplets

- ceph_iscsi_config/settings.py
- rbd-target-api.py
- rbd-target-gw.py
With this PR, `rbd-target-api` / `rbd-target-gw` logger level will be configurable (defaults to 'DEBUG').
> Logger level should be configurable

- rbd-target-api.py
Due to the fact that disk creation (`/api/_disk` endpoint) [is only executed in the local gw](https://github.com/ceph/ceph-iscsi/blob/master/rbd-target-api.py#L987), we have to force a config refresh when adding a disk to a target, otherwise, we may face the following error on other gateways:
```
File "/usr/bin/rbd-target-api", line 839, in _target_disk
disk_config = config.config['disks'][disk]
KeyError: 'rbd/lun1'
```
> Fix race condition on target disk add

- usr/lib/systemd/system/rbd-target-api.service
- usr/lib/systemd/system/rbd-target-gw.service
Newer versions of systemd will return error when trying to start
rbd-target-gw, because it detects ordering and dependency issue
with rbd-target-api.
This removes the bind/wants between the 2 services. The bind/wants was
not required and was added to make it more convenient for users so that
the services stopped and restarted together. I can just doc this instead.
> rbd-target-gw/api systemd dep fix

- rbd-target-api.py
This PR fixes the following error when trying to execute `/iscsi-target...-gw:iscsi-igw> reconfigure cmdsn_depth 512` on a python3 environment:
```
2019-05-24 09:50:21,629    ERROR [rbd-target-api:114:unhandled_exception()] - Unhandled Exception
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.6/site-packages/ceph_iscsi-3.0-py3.6.egg/EGG-INFO/scripts/rbd-target-api", line 107, in decorated
File "/usr/lib/python3.6/site-packages/ceph_iscsi-3.0-py3.6.egg/EGG-INFO/scripts/rbd-target-api", line 331, in target
File …
```
> Fix python3 issue when running target reconfigure

- ceph-iscsi.spec
For pre-RHEL8 environments, use the old school style of handling
systemd.
> spec: partial revert of systemd-rpm-macros to support RHEL 7

- ceph-iscsi.spec
rbd-target-api requires ssl, so add it to the spec file.
There is some weirdness here in that in RHEL 7 the package is named
pyOpenSSL, but in suse and RHEL8 and modern Fedora versions the package
was renamed to python-pyOpenSSL/python2-pyOpenSSL for the python2 based
package. In python3 it is always name python3-pyOpenSSL for all distros.
> Fix openssl rpm dep

- ceph-iscsi.spec
35f0532990356e00e79656a8cdae379885be8725 introduced the following conditional:
```    
%if 0%{?rhel} < 8
...
%endif
```
This is problematic because the conditional will evaluate to true if the macro
`%rhel` is undefined, which is the case on openSUSE for example.
> spec: fix rhel conditional blocks

- ceph-iscsi.spec
- ceph_iscsi_config/utils.py
- rbd-target-api.py
This PR adds SUSE to the list of supported OS.
By default, we are now relying on `/etc/os-release` to get the release version, but for 'redhat', we are still using `platform.linux_distribution` because it has more precision (it also returns the release minor version), but note that `platform` is deprecated so this should be adapted in the future. 
Additionally, the `rpm` version checks on the REST API were moved to the `spec` file only.
> SUSE is now supported

- ceph-iscsi.spec
The changes introduced in commit 9637223b9d8cee3abc527f58fc9e14a1bcbe4b29
are first available in that release.
> spec: actually requires rtslib >= v2.1.fb68

- ceph-iscsi.spec
- etc/systemd/system/rbd-target-gw.service.d/dependencies.conf
Since we moved startup to rbd-target-api, it no longer has a dep on
rbd-target-gw, so drop the systemd dependencies.conf.
This fixes cycle detected bugs that depending on the systemd version
prevent rbd-target-api or rbd-target-gw from starting.
> Fix systemd rbd-target-gw deps

- ceph_iscsi_config/target.py
Deleting a target that has clients/disks results in a portal being removed from `gateway.conf` but not from the `LIO`.
How to reproduce
1) Create a target with disks/clients
2) Confirm that you have >= 2 portals on `gateway.conf` by running `gwcli / export`
3) Try to delete that target, you will see an expected error: 
```
/iscsi-targets> delete iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw
CMD: /iscsi delete iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw
Failed - failed on node1. Clients(1) and disks(1) must be removed before the gateways
```
4) Verify that one portal was **incorrectly** removed from the `gateway.conf` by running `gwcli / export` again
> Fix problem deleting target that contains clients/disks

- ceph_iscsi_config/utils.py
in centos 7 host, there is serveral blank lines, we should skip
these blank lines to pass the os check.
Signed-off-by: wuxingyi <wuxingyi2015@outlook.com>
> fix problem in parse blank lines in /etc/os-release

- ceph_iscsi_config/settings.py
- ceph_iscsi_config/utils.py
- gwcli/utils.py
- rbd-target-api.py
Only some settings are required to be in sync between gateways so, instead of forcing the whole config file to be the same in all gateways, this PR will only consider the settings that really have to be in sync.
With this PR will be possible, for instance, to have different `cluster_client_name` on each gateway.
> Fix config hash check validation 

- ceph-iscsi.spec
- gwcli/gateway.py
- gwcli/utils.py
- rbd-target-api.py
When using `ceph-iscsi` REST API directly (e.g. from Ceph Dashboard) multiple IPs for a single gateway is already supported (if `skipchecks` is set to `true`), but `gwcli` only accepts one IP.
This PR changes the `gwcli` to also accept multiple comma separated IPs (without the need to set `skipchecks=true`).
E.g.:
```
/iscsi-target...0343/gateways> create node1 192.168.100.201,192.168.121.236 
```
Note that `configshell-fb` only supports `,` since https://github.com/open-iscsi/configshell-fb/commit/341018797fcb47bdeda1a5c87266d4b14f51c945 which means that multiple IPs on `gwcli` requires `configshell-fb` >= `v1.1.fb25` (single IP gateways will still work when using older versions of `configshell-fb`)
> Adds support for multiple IPs per gateway on gwcli

- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/lun.py
- ceph_iscsi_config/settings.py
- ceph_iscsi_config/utils.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
- test/test_common.py
With this PR will be possible to use FQDNs instead of host shortnames.
If `fqdn_enabled` setting is `true` (defaults to `false`), then FQDN will be used, otherwise, nothing changes from the previous implementation.
> Add support for enabling FQDN

- ceph-iscsi.spec
systemd-rpm-macros was recently broken off from systemd into its own
package. It is in Fedora but not yet in RHEL 8. This checks for RHELs
less than 8 assuming that in RHEL 9 we will have syncd up with fedora
and will have systemd-rpm-macros.
> Fix spec for RHEL 8 builds

- ceph_iscsi_config/common.py
The upgrade from config version 9 to 10 might result in the
removal of all gateways if the gateway FQDNs are the same as
the hostnames.
> Handle the case where FQDN is the same as hostname

- ceph_iscsi_config/settings.py
- rbd-target-api.py
- test/test_settings.py
This PR will validate if control values meet the requirements described in PR https://github.com/ceph/ceph-iscsi-cli/pull/147:
Additionally, the limits for each control are now returned by the API so REST consumers like Ceph Dashboard can validate the inputs beforehand (https://github.com/ceph/ceph/pull/28942).
> Validate controls min/max value

- ceph_iscsi_config/gateway.py
It is possible that between the time we do a
ceph osd blacklist ls
call and while we are deleting our blacklist entries an entry can
expire. In this case do not exit with error.
> Fix blacklist cleanup error handling

- ceph_iscsi_config/utils.py
When we added ipv6 support we added a call:
socket.getaddrinfo(....socket.AF_INET6)
Some configs might not have ipv6 name resolutions setup correctly so
this causes us to have to wait for a timeout for every REST api call.
In some situations it may not be possible to fix DNS, so this just has
us use socket.getaddrinfo with no faimily then loop over the returned
adds and check for the specific familys we support. It is going to be a
little less efficient, but we will normnally only get AF_INET and
AF_INET6 addresses.
> Fix ipv6 resolutions

- rbd-target-api.py
When an object does not exist, `ceph-iscsi` should return an HTTP 404  code, instead of 400.
By returning `404`, consumers of the API will be able to gracefully handle the case where the object does not exist.
> Fix "not found" HTTP response code on *info endpoints

- rbd-target-api.py
This PR will add the control "type" to the "control_limits" response.
By returning the control "type", Ceph Dashboard (or any other consumer) will be able to render the most appropriate UI component to visualize or edit the "control".
> Controls API should return the corresponding "types"

- ceph_iscsi_config/client.py
- ceph_iscsi_config/common.py
- ceph_iscsi_config/gateway.py
- ceph_iscsi_config/lun.py
- ceph_iscsi_config/target.py
- gwcli/client.py
- gwcli/gateway.py
- gwcli/utils.py
- rbd-target-api.py
- test/test_common.py
This PR contains 2 different commits to fix both topics discussed on issue https://github.com/ceph/ceph-iscsi/issues/130
**1. Target level CHAP authentication**
It's now possible to define CHAP/MUTUAL_CHAP authentication at the target level (same credentials are applied to all TPGs).
When using ACL, those credentials will be inherited and can be overridden at the client level.
**2. Persist TPG lun_id**
Instead of relying on storage object path to generate it, TPG `lun_id` will now be persisted in the `gateway.conf` ensuring that the TPG `lun_id` is the same in all gateways, and will not change across restarts.
Fixes https://github.com/ceph/ceph-iscsi/issues/130
> Target level CHAP authentication and TPG lun_id persistence

- ceph_iscsi_config/client.py
- ceph_iscsi_config/gateway_object.py
- ceph_iscsi_config/gateway_setting.py
- ceph_iscsi_config/lun.py
- ceph_iscsi_config/settings.py
- ceph_iscsi_config/target.py
- gwcli/gateway.py
- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
The lio/ceph-iscsi settings values, limits, and definitions are spread all over. This moves it all to a new file and tries to remove a lot of the duplicated loops/checks/conversion/normalization code.
> ceph-iscsi settings cleanup

- ceph-iscsi.spec
Fix
Sep 25 12:12:29 iscsi-gw0 rbd-target-api[9959]: import requests
Sep 25 12:12:29 iscsi-gw0 rbd-target-api[9959]: ImportError: No module named requests
python-requests used to be brought in my ceph-common, so we never
noticed we were missing out dep on it. This adds it to the spec
> Add python requests

- ceph_iscsi_config/common.py
If the Rados() fails the __init__ function returns an error. The caller
then prints out the error_message and __del__ is called. This then
results in a crash because self.cluster failed to get set. This fixes
the bug by initializing it to None. It also adds a more descriptive
error message.
> Fix crash when CephCluster fails to get Rados object

- rbd-target-api.py
When we switched to using /etc/os-release to get the dist value we broke
red hat based distros. The problem is that the 'ID' value for Red Hat
Enterprise Linux is rhel, but we left the old
platform.linux_distribution value 'redhat' in the dist table.
> Fix RHEL detection in checkversions

- ceph_iscsi_config/client.py
- ceph_iscsi_config/group.py
- ceph_iscsi_config/lun.py
- gwcli/client.py
- gwcli/hostgroup.py
- gwcli/storage.py
- rbd-target-api.py
This PR will allow the user to optionally specify the **LUN number** and **WWN**.
Note that if not explicitly set, then the LUN number and WWN will be automatically generated.
With this change `"ceph-iscsi" + "Ceph Dashboard"` will reach feature parity with `"lrbd" + "openATTIC"`. 
Just for reference, here is a print screen from the openATTIC:
Also, this PR adds a new `api_version` field to the settings endpoint response so consumers of the API can have more control on how to consume the API.
This `api_version` should be incremented every time the API changes.
> Allow explicit set LUN number and WWN

- ceph_iscsi_config/gateway_setting.py
Since https://github.com/ceph/ceph-iscsi/pull/143 it's no longer possible to create targets with a single gateway.
This PR changes the minimum value of `minimum_gateways` to `1` (default value is still `2`).
> Should be possible to use a single gateway

- ceph_iscsi_config/group.py
In a **python3** environment, I have the following configuration:
```
/iscsi-target...t-groups/myg1> ls ../..
o- iqn.2001-07.com.ceph:1571910286153 .................................................................... [Auth: None, Gateways: 2]
o- disks .............................................................................................................. [Disks: 3]
| o- rbd/img1 .......................................................................................... [Owner: node1.ceph.local]
| o- rbd/img2 .......................................................................................... [Owner: node2.ceph.local]
| o- rbd/img3 .......................................................................................... [Owner: node1.ceph.local]
o- gateways …
```
> Fix group disk add on python3

- gwcli/ceph.py
excute command  gwcli,the output as follow 
Gathering pool stats for cluster 'ceph'
File "/usr/bin/gwcli", line 194, in <module>
main()
File "/usr/bin/gwcli", line 105, in main
root_node.refresh()
File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/gwcli/gateway.py", line 76, in refresh
File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/gwcli/ceph.py", line 61, in refresh
File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/gwcli/ceph.py", line 272, in refresh
File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/gwcli/ceph.py", line 309, in update
File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/gwcli/ceph.py", line 302, in _calc_overcommit
ZeroDivisionError: float division by zero
cluster …
> Fix ZeroDivisionError

- ceph_iscsi_config/common.py
If there is no target defined we will crash when upgrading from to 2 to
3. This modifies the version 3 upgrade so we do not assume there will
always be a target defined.
> Fix config upgrade from 2 to 3

- ceph_iscsi_config/metrics.py
some_generator.next() does not exist in python 3. We only have
next(some_generator) which luckily also works in 2, so this patch
converts us to use it.
> Fix next() use crash in rbd-target-gw metrics

- ceph_iscsi_config/gateway.py
- gwcli/gateway.py
- rbd-target-api.py
The first patch fixes the issue where if a gw is dead, we can't delete it because we normally update the config on the node we are updating. The other patches fix some bugs/issues found while testing it.
> Add option to force deletion of unreachable gw

- rbd-target-api.py
This PR fixes rbd-target-api TypeErrors when calling .keys() method.
Originally, any API call which uses that method will fail with: "TypeError: Object of type dict_keys is not JSON serializable". Enclosing with list() resolves that issue.
Added Ubuntu 19.10 to read_os_release dict.
Fixes #166 #167
> Support keys() with python 3

- ceph_iscsi_config/gateway.py
- ceph_iscsi_config/metrics.py
- rbd-target-api.py
- rbd-target-gw.py
This fixes some misc bugs:
1. If no targets are mapped to a gateway rbd-target-gw crashes.
2. rbd-target-api crashes in python3 setups if there are blacklist entries.
3. gateway deletion does not fully cleanup the kernel on the local node.
> Misc fixes

- ceph_iscsi_config/gateway.py
I am not sure if it could always happen or it is a change in python3,
but while testing the blacklist clean up code with python3 we
sometimes do not see the blacklist get fully cleaned up. The problem
is that sometimes blacklist.decode() will change the order of the
returned items so the "list N entries" string. When we look over the
output we then skip the first one and it does not get cleaned up.
> Fix ceph blacklist ls test

- rbd-target-api.py
Ubuntu 18.04 supplies later Linux kernels as part of hardware
enablement, with kernels up to and including 5.3 being avaliable
for use.
Drop minimum Ubuntu version from 19.04->18.04 to support use
on the most recent Ubuntu LTS version.
Signed-off-by: James Page <james.page@ubuntu.com>
> ubuntu: drop minimum version requirement to 18.04

- rbd-target-api.py
To fix a Dashboard issue **[1]**, we need to be able to set target controls even if we don't have any client configured yet.
I've noticed that this check was introduced to guarantee that we only accept valid values(https://github.com/ceph/ceph-iscsi/pull/44/commits/f44d18418329d1982031e8baceeeeddf8d0fc715), but since we are now validating control values beforehand **[2]** I think it's safe to drop this check.
We are also bumping the API version so Dashboard can be backward compatible.
**[1]** https://tracker.ceph.com/issues/44659
**[2]** https://github.com/ceph/ceph-iscsi/blob/master/ceph_iscsi_config/gateway_setting.py#L146
> Allow target reconfigure without clients

- rbd-target-api.py
I'm looking at attempting to add iscsi to cephadm, but frankly having
to place the crt and key inside the container makes things a little
harder. While working on adding RGW SSL support to cephadm sage et al,
suggested we should use the mon config-key store the certs[0][1].
So thought why not fo the same here. This will mean when setting up
service in cephadm, an op can either place the certs:
ceph config-key put 'iscsi/<client-name>/iscsi-gateway.crt -i <file>
ceph config-key put 'iscsi/<client-name>/iscsi-gateway.key -i <file>
Or if given the files via cephadm we can place them on their behalf.
[0]- https://github.com/ceph/ceph/pull/32951
[1]- https://github.com/ceph/ceph/pull/33287
Signed-off-by: Matthew Oliver <moliver@suse.com>
> iscsi: Attempt to pull SSL crt and key's from mon config-key store

- ceph_iscsi_config/gateway_setting.py
- rbd-target-api.py
Most the other ceph components have an option to get them to log to
stderr. And this is used when containerising to help gather logs.
This patch adds a config options `log_to_stderr`, `log_to_stderr_prefix`
and `log_to_file` to do the same for ceph-iscsi. These are matching the
other ceph daemon's:
--default-log-to-stderr=true --default-log-stderr-prefix="debug "
--default-log-to-file=false
Signed-off-by: Matthew Oliver <moliver@suse.com>
> Add a config option to log to stderr

- ceph-iscsi.spec
The "ceph" CLI tool is required for removing blacklist entries.
Resolves: #192
> spec: added dependency on ceph-common package

- ceph_iscsi_config/common.py
- ceph_iscsi_config/gateway_setting.py
- iscsi-gateway.cfg_sample
Add the option to specify the gateway  configuration file, which can configure multiple gateways config  in the same pool.
Signed-off-by: zhang daolong <zhangdaolong@fiberhome.com>
> Support specified gateway config name

- ceph_iscsi_config/lun.py
Fix #205 
When delete the disk which does not have owner field, we will meet the key Error.
This patch is to fix this
> fix delete disk error when disk owner is not specified

- gwcli/gateway.py
- gwcli/utils.py
This propose fix issue: https://github.com/ceph/ceph-iscsi/issues/193
When setting api_host to localhost will hit below crash[1] in python3.
Json response should be encoded into utf-xx bytes[2].
And also add an error handling path for hostname api request.
[1]: 
/iscsi-target...ndev/gateways> create devstack-20-2 192.168.122.174
skipchecks=true
CMD: ../gateways/ create devstack-20-2 ['192.168.122.174'] nosync=False
skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
Gateway creation successful
Adding gw to UI
File "/usr/bin/gwcli", line 194, in <module>
main()
File "/usr/bin/gwcli", line 125, in main
shell.run_interactive()
File "/usr/lib/python3/dist-packages/configshell_fb/shell.py",
line 900, …
> Fix gateway creation crash in python3

- README.md
- ceph_iscsi_config/gateway.py
- rbd-target-api.py
As a followup to Sage's ceph change[0], this patch changes:
blacklist -> blocklist
The most important part is when we call `ceph osd blacklist {ls,rm}`
because it's now actaully `ceph osd blocklist ...`.
So this patch corrects this so ceph-iscsi will work in cephadm on
current master.
[0] - https://github.com/ceph/ceph/commit/dfd01d765304ed8783cef613930e65980d9aee23
Signed-off-by: Matthew Oliver <moliver@suse.com>
> Rename blacklist to blocklist

- ceph_iscsi_config/gateway_setting.py
- test/test_settings.py
Currently when you specify a list in ceph-iscsi it _MUST_ be in the form
of 'item1,item2,item3'. Just delimitted by a comma (,). So if you
specify trusted_ip_list with spaces:
trusted_ip_list: '10.1.1.1, 10.1.1.2'
This is actually fail as the space before 10.1.1.2 is retained.
This patch adds a strip() to the normalise call removing any extra
whitespace from the start and end of each item in the list.
Fixes: https://github.com/ceph/ceph-iscsi/issues/219
Signed-off-by: Matthew Oliver <moliver@suse.com>
> Add a strip to ListSetting.Normalize

- ceph_iscsi_config/gateway_setting.py
- iscsi-gateway.cfg_sample
The default value should be "gateway.conf".
Fixes: https://tracker.ceph.com/issues/48391
> Fix the default value for gateway_conf

- rbd-target-api.py
~~If the crt or key pulled from the mon store is a string object
this will encode it into bytes so it can be written to a temp file.
If the crt or key are already bytes it should have no effect~~
This change opens the temp files in 'w' mode rather than 'w+b' mode
so it can handle writes with strings
Was trying to add an iscsi service to a cephadm cluster using a spec file like so https://pastebin.com/nQ26yuWK
(same format for cert/key as is used for rgw service here https://github.com/ceph/ceph/pull/32951/files#diff-5b67faad3b657e6375889a9a68b5f18833c6ed77f29146875884d15453f81e90R13) 
The container would fail with this error
~~This change gets around that issue and shouldn't cause any problems if a byte object is received to begin with.~~
Signed-off-by: Adam King <adking@redhat.com>
> iscsi: write cert/key to temp files in mode 'w' to handle strings

- rbd-target-api.py
The Config class will create a empty 'gateway.conf' object at the
begining if it doesn't exist. It should be buggy if it doesn't
exist here.
> iscsi: raise if the 'gateway.conf' config file doesn't exist

- ceph_iscsi_config/device_status.py
d0f023a6a19ab2ce619826bac4bf93ffb42dc272 introduced a small typo in a
warning message when there's no tcmu-runner data available.
This commit fixes it.
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
> device_status: fix a typo

- gwcli.py
AttributeError: 'Settings' object has no attribute 'api_endpoint'
> gwcli: fix api_endpoint AttributeError

- gwcli/ceph.py
Show the pool profile instead of size/min_size.
> gwcli: fix the erasure pool profile's display info

- gwcli.8
- gwcli/client.py
- gwcli/gateway.py
- gwcli/hostgroup.py
Update the man page, help text and remaining error messages
for multiple iSCSI targets support added in commit 4f726b188cdf ("Add
support for multiple iSCSI targets").
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
> gwcli: iscsi-target -> iscsi-targets

- gwcli/gateway.py
The 401 means the user/password mismatch, and 403 means the requested
ip address is not in the trusted ip list and use the "Forbidden" will
be clearer and could easily distinguish from the 401 error.
> gwcli: switch 403 state status to FORBIDDEN

- ceph-iscsi.spec
Ceph cluster now incorporates a generic metric gathering framework
within the OSDs and MGRs to provide built-in monitoring.
> spec: mark the ceph-iscsi-tools package deprecated

- rbd-target-api.py
Check the werkzeug major version as well as the minor version when
deciding which type of SSL context. Closes #255
> Improve werkzeug version checking

- ceph_iscsi_config/lun.py
valid_disk() should return either "ok" or an error description
string.  However, in case controls normalization fails, ValueError
object is returned.
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
> lun: fix valid_disk() return value

- rbd-target-api.py
- rbd-target-gw.py
The request.is_xhr method has been deprecated & removed, as it was
unreliable.
> disable JSONIFY_PRETTYPRINT_REGULAR in flask app config

- ceph-iscsi.spec
rtslib now requires /etc/target or /var/target to be setup (it depends on the version). The issue is that rtslib does not make those dirs and instead relies on targetcli or ceph-iscs to make them.
For container cases we do not install targetcli, so ceph-iscsi's daemons will crash or fail to setup disks, when we make rtslib calls that try to access the etc/var target dirs.
When rtslib is fixed drop this and update the dep. Note that we add both etc and var, because the kernel and userspace developers keep switching the dir they want to use.
> spec: make sure we always have the target dir

- ceph-iscsi.spec
- gwcli/client.py
- rbd-target-api.py
- test/test_common.py
The 'platform.linux_distribution()' has been deprecated since python 3.7. And we should switch to use the distro.version(), distro.id() and distro.name() instead.
> rbd-target-api: switch to use distro to get the release version

- ceph_iscsi_config/device_status.py
```
Exception in thread Thread-2:
File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/site-packages/ceph_iscsi_config/device_status.py", line 162, in run
stats_dict = dev_status.get_status_dict()
AttributeError: 'NoneType' object has no attribute 'get_status_dict'
```
> device_status: avoid AttributeError when logging debugging info

- test/test_chap.py
- test/test_common.py
https://github.com/testing-cabal/mock
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
> Prefer the newer unittest.mock from the standard library on Python 3
